export const SAMPLE_COURSES = [
  {
    id: "sample-1",
    title: "Full Stack Web Development",
    category: "Development",
    duration: "12 Weeks",
    students: "1,200+",
    rating: 4.9,
    price: "₹14,999",
    description: "Master modern web technologies from HTML/CSS to React and Node.js. Build real-world projects and deploy them.",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-2",
    title: "Data Science & Machine Learning",
    category: "Data Science",
    duration: "16 Weeks",
    students: "850+",
    rating: 4.8,
    price: "₹19,999",
    description: "Learn to analyze data, build predictive models, and master Python for data science and AI applications.",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-3",
    title: "UI/UX Design Masterclass",
    category: "Design",
    duration: "8 Weeks",
    students: "500+",
    rating: 4.7,
    price: "₹9,999",
    description: "Design beautiful and functional user interfaces. Master Figma, user research, and prototyping techniques.",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-4",
    title: "Digital Marketing Strategy",
    category: "Marketing",
    duration: "6 Weeks",
    students: "2,000+",
    rating: 4.6,
    price: "₹7,999",
    description: "Grow businesses with SEO, SEM, social media marketing, and content strategy. Learn data-driven marketing.",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-5",
    title: "Cloud Computing with AWS",
    category: "Cloud",
    duration: "10 Weeks",
    students: "600+",
    rating: 4.8,
    price: "₹12,999",
    description: "Master cloud infrastructure, serverless computing, and deployment strategies using Amazon Web Services.",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-6",
    title: "Cyber Security Essentials",
    category: "Security",
    duration: "12 Weeks",
    students: "400+",
    rating: 4.9,
    price: "₹15,999",
    description: "Protect systems from cyber threats. Learn ethical hacking, network security, and risk management.",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-7",
    title: "React.js Masterclass",
    category: "Development",
    duration: "8 Weeks",
    students: "1,500+",
    rating: 4.9,
    price: "₹8,999",
    description: "Build modern, interactive web applications using React, Hooks, Redux, and Next.js.",
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-8",
    title: "Core Java Programming",
    category: "Development",
    duration: "10 Weeks",
    students: "2,200+",
    rating: 4.7,
    price: "₹7,499",
    description: "Master object-oriented programming with Java. Covers core concepts, collections, and multithreading.",
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-9",
    title: "Python for Beginners",
    category: "Development",
    duration: "6 Weeks",
    students: "3,000+",
    rating: 4.8,
    price: "₹5,999",
    description: "Start your coding journey with Python. Learn syntax, data structures, and build basic applications.",
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bfce8?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-10",
    title: "Advanced C++",
    category: "Development",
    duration: "8 Weeks",
    students: "900+",
    rating: 4.6,
    price: "₹8,499",
    description: "Deep dive into C++ memory management, pointers, STL, and advanced object-oriented design.",
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "sample-11",
    title: "C Programming Fundamentals",
    category: "Development",
    duration: "6 Weeks",
    students: "1,800+",
    rating: 4.5,
    price: "₹4,999",
    description: "Learn the mother of all programming languages. Understand logic building, arrays, and functions.",
    isFeatured: false,
    image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&q=80&w=800"
  }
];
